### ISSUE TITLE
移动端半选

### ISSUE THREAD

**Issue by hasbug** [luyilin/vue-cute-rate#2]
设置了半选，但在手机端没效果···

**Comment by luyilin** [comment]
我刚刚试了一下可以啊，可以给一个 codepen 链接什么的吗？
注意 ```:star-half="true"``` star-half 需要前需要加冒号值才是布尔值，这个地方设置对了吗？

**Comment by hasbug** [comment]
@luyilin 就是设置的布尔值，奇怪，每次都是整颗星。项目有点大，还在线下 没有可运行的线上代码···我再自己看看
